services:
  db:
    image: postgres:16
    container_name: rbac_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rbac_db_test
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rbac_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://admin:admin@db:5432/rbac_db_test}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-True}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rbac_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  dbdata:
